repos:
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      stages: [commit]
      types: [python]
      language: system
      pass_filenames: false
      entry: sh -c "cd DCSStatsDataProvider && pytest"
      always_run: true