repos:
  - repo: local
    hooks:
      - id: run-tests
        name: run-tests
        entry: sh -c "python -m pytest && echo 'pytests passed.'" || (echo 'pytests failed' && false)
        language: system
        files: .py
