version: "3.3"
services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - "--log.level=DEBUG"
      - "--api=true"
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--log.filePath=/etc/traefik/log/traefik.log"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      # Enable ACME (Let's Encrypt): automatic SSL.
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=$EMAIL"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme/acme.json"
      # Global redirect to https
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.traefik.address=:8080"
      - "--providers.docker.network=$DEFAULT_NETWORK"
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.api.entryPoints=traefik"
    - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
    - "traefik.http.routers.api.service=api@internal"
    - "traefik.http.routers.api.middlewares=api-auth"
    - "traefik.http.middlewares.api-auth.basicauth.users=$DASHBOARD_LOGIN"

    volumes:
      - ./letsencrypt/acme.json:/etc/traefik/acme/acme.json
      - ./traefik/traefik.log:/etc/traefik/log/traefik.log
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - traefik_net
    restart: unless-stopped


  dcsstats:
    image: woulve/dcsstatsbackend:$PLATFORM
    ports:
      - 8000:8000
    volumes:
      - ./serverlog.log:/DCSStats/serverlog.log
      - ./config.cfg:/DCSStats/config.cfg
      - ./src/util/realweather/:/DCSStats/src/util/realweather/
      - ./SlmodStats.lua:/DCSStats/SlmodStats.lua
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcsstats.rule= Host(`$MY_DOMAIN`)"
      - "traefik.http.routers.dcsstats.entrypoints=websecure"
      - "traefik.http.routers.dcsstats.tls=true"
      - "traefik.http.routers.dcsstats.tls.certresolver=letsencrypt"
    networks:
      - traefik_net
    restart: unless-stopped

networks:
  traefik_net:
      name: $DEFAULT_NETWORK
      external: true