version: "3.3"

services:

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./volumes/traefik/acme:/acme
      - ./volumes/traefik/logs:/logs
      - ./letsencrypt:/letsencrypt
    restart: unless-stopped


  dcsstats:
    image: woulve/dcsstatsbackend:latest
    volumes:
      - ./serverlog.log:/DCSStats/serverlog.log
      - ./config.cfg:/DCSStats/config.cfg
      - ./src/util/realweather/:/DCSStats/src/util/realweather/
      - ./SlmodStats.lua:/DCSStats/SlmodStats.lua
    ports:
      - "8000:8000"
    environment:
      - TZ=Europe/Berlin
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dcsstats.rule= Host(`shithonse.strangled.net`)"
      - "traefik.http.routers.dcsstats.entrypoints=web"
      # - traefik.http.routers.dcsstats.tls.certresolver=letsencrypt
    restart: unless-stopped