{
 "title": "New dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "job", "label": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "protocol",
    "label": "Service:",
    "query": {
     "query": "label_values(traefik_service_requests_total, protocol)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "service", "query": { "query": "label_values(service)" } },
   { "name": "query0", "label": "entrypoint", "query": { "query": "label_values(entrypoint)" } }
  ]
 },
 "panels": [
  {
   "title": "Traefik Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus\", instance=\"traefik:8080\"}"
    }
   ]
  },
  {
   "title": "Top 5 $protocol return code",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(5, sum(traefik_service_requests_total{protocol=~\"$protocol\"}) by (code))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "500 Error count",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{code=\"500\",protocol=~\"$protocol\"}[$interval]))"
    }
   ]
  },
  {
   "title": "500 Error count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(traefik_entrypoint_requests_total{code=\"500\",protocol=~\"$protocol\"}[$interval]))",
     "legendFormat": "GET : 500"
    }
   ]
  },
  {
   "title": "Others status code",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "traefik_entrypoint_requests_total{code!=\"200\"}",
     "legendFormat": "{{ method }} : {{code}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_requests_total) by (protocol)",
     "legendFormat": "{{ protocol }}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(traefik_entrypoint_requests_total[$interval]))",
     "legendFormat": "Total requests"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(traefik_entrypoint_request_duration_seconds_sum) / sum(traefik_entrypoint_requests_total) * 1000"
    }
   ]
  },
  {
   "title": "Average response time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 21, "x": 3, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(traefik_service_request_duration_seconds_sum{protocol=~\"$protocol\"}) / sum(traefik_entrypoint_requests_total{protocol=~\"$protocol\"}) * 1000",
     "legendFormat": "Average response time (ms)"
    }
   ]
  },
  {
   "title": "Status Code Count ",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(traefik_service_requests_total{protocol=~\"$protocol\"}[$interval])) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}