name: Pytest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.6'
          # Optional - x64 or x86 architecture, defaults to x64
          architecture: 'x64'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r DCSStatsDataProvider/requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest uvicorn
          cd DCSStatsDataProvider
          pytest --rootdir=.